server:
  port: ${serverPort:8080}
spring:
  jmx:
    enabled: off
  application:
    name: Lego Data Service

lego:
  data:
    enabled: true
  marketplace-listing-drafts:
    production: ${MARKETPLACE_LISTING_DRAFTS_PRODUCTION:false}
    environment-code: ${MARKETPLACE_LISTING_DRAFTS_ENVIRONMENT_CODE:local}
    non-prod-bricklink-stockroom-id: ${MARKETPLACE_LISTING_DRAFTS_NON_PROD_BRICKLINK_STOCKROOM_ID:C}

management:
  info:
    git:
      enabled: true
      mode: full

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,startup

aws-credentials:
  client-config-dir: C:\Users\tvatt\.credentials\aws
  client-config-file: aws-iam-credentials.json

aws-iam-roles-anywhere:
  client-config-dir: C:\Users\tvatt\.credentials\aws
  client-config-file: aws-iam-roles-anywhere.json

flickr:
  client-config-dir: C:\Users\tvatt\.credentials\flickr.api
  client-config-file: flickr-client-api-keys.json
  application-name: lego-imaging
  debug-request: false
  debug-stream: false

bitly:
  client-config-dir: C:\Users\tvatt\.credentials\bitly.api
  client-config-file: bitly-client-api-keys.json

events:
  queues:
    user-created-by-name-queue: sandbox-sqs-queue

logging:
  level:
    root: INFO
