import-path: /dev/config

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: false
  defaults:
    metrics:
      export:
        enabled: false

otel:
  sdk:
    disabled: true

logging:
  level:
    org.springframework.core.env: TRACE
    org.springframework.boot.context.config: DEBUG
    com.zaxxer: DEBUG
