apiVersion: v1
kind: Service
metadata:
  name: lego-data-service
  labels:
    app.kubernetes.io/name: lego-data-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: lego-platform
spec:
  type: ClusterIP
  selector:
    app: lego-data-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
